apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.datatunerxUi.service.name }}
  namespace: {{ .Values.datatunerxUi.namespace }}
  labels:
    datatunerx.io/component: ui
    datatunerx.io/part-of: datatunerx
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "6"
spec:
  type: {{ .Values.datatunerxUi.service.type }}
  ports:
    - port: 8443
      protocol: TCP
      targetPort: 8443
  selector:
    datatunerx.io/component: ui
