apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.datatunerxUi.serviceAccountName }}
  namespace: {{ .Values.datatunerxUi.namespace }}
  labels:
    datatunerx.io/part-of: datatunerx
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "1"
