apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Values.finetuneController.clusterRoleName }}
  labels:
    datatunerx.io/part-of: datatunerx
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "20"
rules:
- apiGroups:
    - ""
  resources:
    - events
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - ray.io
  resources:
    - rayjobs
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - ray.io
  resources:
    - rayjobs/status
  verbs:
    - get
- apiGroups:
    - batch
  resources:
    - jobs
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - coordination.k8s.io
  resources:
    - leases
  verbs:
    - create
    - get
    - list
    - update
    - delete
    - watch
- apiGroups:
    - finetune.datatunerx.io
  resources:
    - finetunes
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - finetune.datatunerx.io
  resources:
    - finetunes/status
  verbs:
    - get
    - update
- apiGroups:
    - core.datatunerx.io
  resources:
    - llmcheckpoints
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - core.datatunerx.io
  resources:
    - llmcheckpoints/status
  verbs:
    - get
- apiGroups:
    - core.datatunerx.io
  resources:
    - hyperparameters
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - core.datatunerx.io
  resources:
    - hyperparameters/status
  verbs:
    - get
    - update
- apiGroups:
    - core.datatunerx.io
  resources:
    - llms
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - core.datatunerx.io
  resources:
    - llms/status
  verbs:
    - get
    - update
- apiGroups:
    - extension.datatunerx.io
  resources:
    - datasets
  verbs:
    - create
    - delete
    - get
    - list
    - patch
    - update
    - watch
- apiGroups:
    - extension.datatunerx.io
  resources:
    - datasets/status
  verbs:
    - get
    - update
- apiGroups:
    - ""
  resources:
    - pods
  verbs:
    - get
    - list
    - watch
- apiGroups:
    - ""
  resources:
    - pods/exec
  verbs:
    - create
