apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.finetuneExperimentController.clusterRoleBindingName }}
  labels:
    datatunerx.io/part-of: datatunerx
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "12"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.finetuneExperimentController.clusterRoleName }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.finetuneExperimentController.serviceAccountName }}
  namespace: {{ .Values.finetuneExperimentController.namespace }}
