apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.finetuneExperimentController.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
  labels:
    datatunerx.io/part-of: datatunerx
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "13"
