apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.finetuneExperimentController.service.name }}
  namespace: {{ .Values.finetuneExperimentController.namespace }}
  labels:
    datatunerx.io/component: finetune-experiment
    datatunerx.io/part-of: datatunerx
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "15"
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    datatunerx.io/component: finetune-experiment
