kuberay:
  enabled: false
minio:
  enabled: false

namespace: datatunerx

global:
  registry: "docker.io"
  repository: "datatunerx"
  imagePullSecret: ""
  imagePullPolicy: Always


datatunerxUi:
  name: datatunerx-ui
  replicas: 1
  image: datatunerx-ui:v0.1.0
  apiUrl: https://kubernetes.default.svc:443
  labels:
  resources:
    limits:
      cpu: 500m
      memory: 0.5Gi
    requests:
      cpu: 500m
      memory: 0.5Gi
  service:
    name: datatunerx-ui
    type: NodePort

  serviceAccountName: datatunerx-ui
  clusterRoleBindingName: datatunerx-ui-binding

finetuneExperimentController:
  labels:
  clusterRoleName: datatunerx-role
  clusterRoleBindingName: datatunerx-binding
  serviceAccountName: datatunerx
  secretName: datatunerx-cert
  mutatingWebhookConfigurationName: datatunerx-mutating-webhook-configuration
  validatingWebhookConfigurationName: datatunerx-validating-webhook-configuration
  name: datatunerx
  replicas: 1
  environment:
    baseImage: datatunerx/ray271-llama2-7b-finetune:v0.1.0
    mountPath: /var/lib/container
    metricsExportAddress: "http://10.33.1.10:30722"
    storagePath: "s3://datatunerx/tuning?endpoint_override=http://10.33.1.10:32575"

  image: datatunerx:v0.1.0
  resources:
    limits:
      cpu: 500m
      memory: 128Mi
    requests:
      cpu: 10m
      memory: 64Mi
  service:
    name: datatunerx

scoringPluginController:
  serviceAccountName: datatunerx-scoringplugin
  clusterRoleBindingName: datatunerx-scoringplugin-binding
  name: datatunerx-scoringplugin
  labels:
  replicas: 1
  image: scoringplugin-controller:v0.1.0
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi

dataPluginController:
  serviceAccountName: datatunerx-dataplugin
  clusterRoleBindingName: datatunerx-dataplugin-binding
  name: datatunerx-dataplugin
  labels:
  replicas: 1
  image: dataplugin-controller:v0.1.0
  resources:
    limits:
      cpu: 200m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi


datatunerxServer:
  name: datatunerx-server
  replicas: 1
  image: datatunerx-server:v0.1.0
  resources:
    limits:
      memory: "512Mi"
      cpu: "2000m"
    requests:
      memory: "256Mi"
      cpu: "1000m"

  service:
    name: datatunerx-server
    type: ClusterIP


s3:
  accessKeyId: admin
  bucket: datatunerx
  endpoint: 10.33.1.10:32575
  secretAccessKey: dN3dz3IFd3
  secure: "false"

registry:
  registryUrl: 10.33.1.11:9090
  repositoryName: datatunerx
  userName: admin
  password: dangerous