apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.finetuneExperimentController.secretName }}
  namespace: {{ .Values.finetuneExperimentController.namespace }}
  labels:
    datatunerx.io/component: finetune-experiment
    datatunerx.io/part-of: datatunerx
  annotations:
    "helm.sh/hook": "pre-install,pre-upgrade"
    "helm.sh/hook-weight": "14"
